server:
  port: 9002

spring:
  application:
    name: ms-order
  data:
    mongodb:
      uri: mongodb+srv://my-user:<Password>@cluster0.kw7fr.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      database: ms-order