server:
   port: 9002

spring:
   application:
      name: payment-service
   data:
      mongodb:
         uri: mongodb://localhost:27017/taller1

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8099/eureka/