server:
  port: 9001

spring:
  application:
    name: ms-payment
  data:
    mongodb:
      uri: mongodb+srv://my-user:user01@cluster0.kw7fr.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      database: ms-payment