server:
   port: 9003
spring:
   application:
      name: order-service
   data:
      mongodb:
         uri: mongodb://localhost:27017/taller1
# Output to a file named application.log.
logging:
   file:
      name: application.log
management:
   metrics:
      export:
         prometheus:
            enabled: true
   endpoint:
      prometheus:
         enabled: true
      health:
         show-details: always
      metrics:
         enabled: true
   endpoints:
      web:
         exposure:
            include: '*'
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8099/eureka/
   instance:
      preferIpAddress: true
      hostname:
         hostname: localhost