server:
  port: 8081

spring:
  application:
    name: ms-product
  data:
    mongodb:
      uri: mongodb+srv://my-user:user01@cluster0.kw7fr.mongodb.net/ms-product?retryWrites=true&w=majority
      database: ms-product